# Generated by Django 3.1.4 on 2020-12-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_auto_20201212_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
